export const ClientRoutesConstants = {
  notFound: "/notFound",
  unauthorized: "/unauthorized",
  dashboard: "/dashboard",
  login: "/login",
  signUp: "/signup",
  otp: "/otp",
  newpage: "/new-page",
  tickets: "/tickets/*",
  createTicket: "create-ticket",
  editTicket: "edit-ticket",
  contatcts: "/contacts",
  superadmin: "/user/super-admin/*",
  createSuperAdmin: "create",
  editSuperAdmin: "edit",
  admin: "/user/admin/*",
  createAdmin: "create",
  editAdmin: "edit",
  deptUser: "/user/department-user/*",
  createDeptUser: "create",
  editDeptUser: "edit",
  userRequest: "/user-request",
  allChats: "/all-chats",
  deptMaster: "/department-master/*",
  createDept: "create",
  editDept: "edit",
  privacyPolicy: "/privacy-policy",
  termAndCondition: "/term&Condtions",
  contactUs: "/contact-us",
  colorGame: "/color-game",
};
export const COLORS = {
  White: '#FFFFFF',
  Black: '#000000',
  Red: '#FF0000',
  RedLight:'#FFEEEE',
  Grey: '#A5A5A5',
  LightGrey: '#EFEFEF',
  DarkGrey: '#585858',
  Orange: '#E88246',
  OrangeLight: '#FFE9D9',
  Pink: '#F5115E',
  Purple: '#7F00FF',
  Blue: '#2196F3',
  BlueLight: '#D9EDFF',
  Green: '#34A853',
  GreenLight: '#E1F5EA',
};